### ISSUE TITLE
We should develop compelling internal & external use cases.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/open-leadership-framework#18]
We should:

- Consider the taxonomy of open projects and their domains' needs from a document like this.
- Develop 3-5 use cases that might address those needs.
- Identify internal and external partners who might test those use cases.
- Document those tests and use them to improve the framework.

*from a conversation with Allen Gunn*

**Comment by chadsansing** [comment]
Would like to involve internal and volunteer communities like MCWS and MDN in addition to external partners. Perhaps drawing 3-5 testers from:

- F/OSS.
-     Open Data.
-     OER.
-     Open Science (as the 5th since we have a lot of this DNA in the project already).

**Comment by chadsansing** [comment]
We might develop use cases like:

- Long-form self-assessments.
- Short-form self-assessments.
- Long form planning canvases.
- Short form planning canvases.
- Long form post mortem surveys.
- Short-form post mortem surveys.
- Fellows training.
- Short form applications surveys.

cc @Saallen

**Comment by Saallen** [comment]
I would also suggest we use the new personas as an initial testing and conversational piece
Lopping in @xmatthewx  who can point you to the latest version

**Comment by chadsansing** [comment]
+1

**Comment by xmatthewx** [comment]
Great idea. Thanks. [Draft personas](https://drive.google.com/file/d/1hboEuUQCdyOSvaN-ejroBNLvoPJaFoJN/view?usp=sharing) are a PDF in drive. 

We'd love any feedback on how they help and how they could be more helpful.

**Comment by chadsansing** [comment]
Many thanks, @xmatthewx - more soon.

**Comment by chadsansing** [comment]
I'm recruiting leaders willing to test the following prototype use cases:

- Project design assessment
- Project post mortem
- Self-asssessment
- Applications short-form

## The ask

Stress test a use-case and write a 250 narrative about the experience - what made sense? what seemed confusing or missing? what did it make you ask, wonder, or think? was it useful? would you recommend it or use it again? how would you improve the use case?

Time commitment:** 2-3 hours

1. Read the Open Leadership Map white paper public beta.
2. Send Chad any questions and feeback you need addressd to feel conversant about it.
3. Complete the use-case survey Chad sent you.
4. Answer the tester questions about your experience with the use case.
5. Share the completed use-case and yur answes to the tester questions back to Chad.
6. Help Chad answer any questions he has about your use-case or narrative.

We would like to share the artifacts you produce as part of the OLM white paper under a CC-BY 4.0 license held by Mozilla. Is that okay? Would you like to be credited by name and role/title, or would you rather be anonymlus with a generic persona or descriptor like "director-level staffer at a non-profit" or "project manager at an open source project?"

## Potential partners & ecosystem niches

- (2) OER community members
- (2) Fellows 
- (1) MDN contributor or staffer
- (1) MCWS or Participation contributor or staffer
- (3) Global Spring project leads
- (3) MIT OLC project leads
- (1) Opensource.com participant
- (1) NGO staffer or community member
- (1) MoFo staffer

I'd like to reach 15 use case examples total by the end of H1.

**Comment by chadsansing** [comment]
Invite revised & sent; use cases sharable as web forms; blog post extending the invitation up by Friday, 2/16/18.

- [Self assessment](https://docs.google.com/forms/d/e/1FAIpQLSds8B2aj6K0h7EwdKDBdqpIkGxReyOgrA4QRhrLim-Ags4rUw/viewform?usp=sf_link)
- [Project design assessment](https://docs.google.com/forms/d/e/1FAIpQLSesg4Uk7Znn5VawGQd99eTIlAsNyPXv9TdLeJhfYj2mxtlv4w/viewform?usp=sf_link)
- [Project postmortem](https://docs.google.com/forms/d/e/1FAIpQLScckWbuQuXut4y_Brp3yTr9dqPVPPwdlaxMyM_8cFLgACSFaA/viewform?usp=sf_link)
- [Applications survey](https://docs.google.com/forms/d/e/1FAIpQLSdPKwWh_3euSwKyjAmJVSKsR_gjBkMsq-SJ48lLGrGicEQo3g/viewform?usp=sf_link)

**Comment by chadsansing** [comment]
Invites sent on 2/14; blog post published on 2/16. Deadline for testing and feedback 3/9.

**Comment by Saallen** [comment]
Hey- I have another technical tester, from MDN so will share intros over emails. 
I have another technical tester but who has no ties to Mofo or our strategy- would this be of interest too?

**Comment by chadsansing** [comment]
Definitely, @Saallen - thanks!

**Comment by stephwright** [comment]
How are you on testers?  I see you sent out invites 2/14... do you still need more?

**Comment by chadsansing** [comment]
@stephwright, could definitely use suggestions for people from different parts of the Open ecosystem like Open Data and Open Hardware. Maybe from Carpentry?

**Comment by chadsansing** [comment]
Will gather more from fox-fooding after an April 2018 brownbag. Also added personas and before and after stories to a use-case page in the CMS site under dvelopment.

**Comment by chadsansing** [comment]
We'll test internally after meting with Mark to discuss strategy and setting up an internal brown-bag. We'll also test with 3-4 GS projects.

Self-assessment, project-design assessment, and project post-mortem have gotten the most interest, so we'll focus on improving those.

Closing.
