### ISSUE TITLE
We should reference technical projects potential users will recognize.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/open-leadership-framework#21]
We should provide examples of technical projects to illustrate more ideas in the white paper so members of such projects will recognize this work as useful to them. The history of F/OSS provides many examples that would be useful for this.

*from a conversation with Allen Gunn*

**Comment by chadsansing** [comment]
Thinking of how we might do this through use cases, as well, with self-assessments or project post mortems from orgs like MCWS, MDN, and external partners.

**Comment by chadsansing** [comment]
Some ideas:

- Firefox
- MDN
- Others? ReMos? MWCS?

Other suggestions?

**Comment by Saallen** [comment]
* David ross would be a good connection here re technical 
*

**Comment by chadsansing** [comment]
Yes - I also want to repurpose Mark's Firefox video.

**Comment by chadsansing** [comment]
Working to include the story of Firefox from [Working Open at Mozilla](https://www.youtube.com/watch?v=quKdaqlR_9w) into the CMS site under development.

**Comment by chadsansing** [comment]
Mozilla and Working Open is in the CMS copy now, and I'm waiting on responses to story/snippet asks of the Project Common Voice team and MDN.

**Comment by chadsansing** [comment]
Closing for now - Common Voice and MDN snippets are in the framework.
