### ISSUE TITLE
We should revise the post-mortem prototype use case.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/open-leadership-framework#26]
Kim Wilkens shared the following suggestions:

- Ask fewer questions.
- Keep the same questions, but make the post-mortem customizable.
- Revise to eliminate jargon.
- Provide examples for others to see.

**Comment by chadsansing** [comment]
I love the idea of making the question pool for customizable in later versions of the use case. I am unsure of whether or not the use case feels jargony, in general, or because it uses so much language from the map, which should be reviewed before use. I asked Kim for clarification via email.

**Comment by Saallen** [comment]
Interesting comment re jargon- has kim reviewed the OLM paper? Is there areas there she feels we are unclear on?

**Comment by chadsansing** [comment]
She had not reviewed the white paper with the students doing the post-mortem, so some of the language was super new to the audience.

**Comment by chadsansing** [comment]
Revised & included in the use-case folder.

Closing.
