### ISSUE TITLE
We should add a reporting page to the self-assessment use case.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/open-leadership-framework#28]
From Edoardo:

> 
> What's missing?
> 
> Probably a final report of the score obtained and some resources helpfull to be more "aligned" at the Open principles, where is necessary.

**Comment by chadsansing** [comment]
@acabunoc, have we been able to do this yet?

**Comment by acabunoc** [comment]
oh I added a sheet in the survey results that show the self-assessment score
Haven't done anything you can see publicly (unless all the results are public)

**Comment by chadsansing** [comment]
cc @acabunoc 

I think we might keep the test cases up for feedback, but attach revised .pdf docs to the next OLF release so that we're not keeping data or maintaining a web form yet.

Closing.
