### ISSUE TITLE
White paper -> Framework updates!

### ISSUE THREAD

**Issue by acabunoc** [mozilla/open-leadership-framework#34]
Places you'll need to update!

* [x] navigation bar contents: https://github.com/mozilla/olm-whitepaper/blob/master/contents.html#L4
* [x] navigation title https://github.com/mozilla/olm-whitepaper/blob/master/_includes/navigation.html#L4
* [x] description at the top of the repo https://github.com/mozilla/olm-whitepaper (hit 'edit')

Config
* [x] title shown in tab: https://github.com/mozilla/olm-whitepaper/blob/master/_config.yml#L1
* [x] description in search preview: https://github.com/mozilla/olm-whitepaper/blob/master/_config.yml#L7
* [x] github will redirect this, but would be good to change it here too if you update the repo name: https://github.com/mozilla/olm-whitepaper/blob/master/_config.yml#L14

**Comment by acabunoc** [comment]
Oh and the last thing is the repo name
<img width="827" alt="screen shot 2018-03-19 at 9 58 50 am" src="https://user-images.githubusercontent.com/617994/37599864-2abf6422-2b5c-11e8-9465-82a340958e17.png">

**Comment by chadsansing** [comment]
Fingers crossed. Will review & close if nothing is broken.

**Comment by chadsansing** [comment]
Lost the sidebar nav.

![screen shot 2018-03-19 at 11 56 37 am](https://user-images.githubusercontent.com/4128600/37606768-a56023aa-2b6c-11e8-8fab-aec78a3be8c3.png)

cc @acabunoc

**Comment by chadsansing** [comment]
Fixed contents reference for the sidebar nav & banner.

**Comment by acabunoc** [comment]
To update the banner, fix the repo name here: https://github.com/mozilla/open-leadership-framework/blob/master/css/main.css#L29

Missed adding that in the checklist! Sorry!

**Comment by acabunoc** [comment]
Also, this search might help you find other broken links:
https://github.com/mozilla/open-leadership-framework/search?utf8=%E2%9C%93&q=olm-whitepaper&type=

**Comment by chadsansing** [comment]
Super helpful, @acabunoc - thank you. Done and done.

Will leave this issue open until next week to see what else shakes loose and needs to be fixed.

**Comment by chadsansing** [comment]
Closing for now. Will file new issues as other legacy/transition issues surface.
